Action Changes

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -204,6 +204,11 @@ runs:
         website_issues_errors=$(a11ywatch --results-issues-errors)
         website_issues_warnings=$(a11ywatch --results-issues-warnings)
 
+        echo "SCAN RESULT:"
+        echo "website_issues_total $website_issues_total"
+        echo "website_issues_errors $website_issues_errors"
+        echo "website_issues_warnings $website_issues_warnings"
+
         total_limit=${{ inputs.FAIL_TOTAL_COUNT }}
         errors_limit=${{ inputs.FAIL_ERRORS_COUNT }}
         warnings_limit=${{ inputs.FAIL_WARNINGS_COUNT }}
@@ -215,21 +220,21 @@ runs:
         if [ "$total_count" -gt 0 ]; then
           if [ $website_issues_total -gt "$total_count" ]; then
               echo "Failed accessibility test. $website_issues_total total errors and warnings exceeded limit!"
-              exit 1
+              # exit 1
           fi
         fi
 
         if [ "$errors_count" -gt 0 ]; then
           if [ $website_issues_errors -gt "$errors_count" ]; then
               echo "Failed accessibility test. $website_issues_errors errors exceeded the limit!"
-              exit 1
+              # exit 1
           fi
         fi
 
         if [ "$warnings_count" -gt 0 ]; then
           if [ $website_issues_warnings -gt "$warnings_count" ]; then
               echo "Failed accessibility test. $website_issues_warnings warnings exceeded limit!"
-              exit 1
+              # exit 1
           fi
         fi
 
@@ -247,6 +252,10 @@ runs:
         results_path="$(a11ywatch --find-results)"
         gh_api_url="$(a11ywatch --github-api-url)"
         website_issues=$(a11ywatch --results-issues)
+
+        echo "POST STATS RESULT PR:"
+        echo "website_issues_total $website_issues"
+        echo "OUTPUT ISSUES: ${{ steps.a11ywatch-results-generator.outputs.issues }}"
 
         # send pr results if issues exist
         if [ "$website_issues" -gt 0 ]; then
